{
 "title": "Example Application Metrics",
 "description": "Application metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"^5..$\"}[1m])) /  sum(increase(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m])) by (job, path, method, status_code)",
     "legendFormat": "{{job}} - {{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Total 5xx Error Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=~\"^Application.*$\",status_code=~\"^5..$\"})"
    }
   ]
  },
  {
   "title": "Total 4xx Error Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=~\"^Application.*$\",status_code=~\"^4..$\",path!~\"/(csp-report|healthz|readyz)\"})"
    }
   ]
  },
  {
   "title": "Total 2xx Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=~\"^Application.*$\",status_code=~\"^2..$\",path!~\"/(metrics|healthz|readyz)\"})"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Median Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, job, path, method))",
     "legendFormat": "{{job}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, job, path, method))",
     "legendFormat": "{{job}} - {{method}} {{path}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Node Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}